import mongoose, { Schema } from "mongoose";
const videoSchema=new Schema(
    {
        videoFile:
        {
            type:String,
            required:true
        },
        thumbNail:
        {
            type:String,
            required:true
        },
        tittle:
        {
            type:String,
            required:true
        },
        description:
        {
            type:String,
            required:true
        },
        view:
        {
            type:Number,
            default:0,
            required:true
        },
        likes:
        {
            type:Number,
            required:true,
            default:0
        },
        duration:
        {
            type:Number,
            required:true
        },
        owner:
        {
            type:Schema.Types.ObjectId,
            ref:"User"
        }
    },
    {
        timestamps:true
    }
);
const Video=mongoose.model("Video",videoSchema);
export {Video};